gitGraph
    commit id: "init"
    commit id: "add-ci"
    branch feature
    commit id: "wip"
    commit id: "tests"
    checkout main
    commit id: "hotfix"
    merge feature id: "v1.0"
    commit id: "release"
